name: Slack Incoming Webhooks
on: [
  pull_request,
  issue_comment,
  pull_request_review,
  pull_request_review_comment
]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check out theis repo
      - uses: actions/checkout@v2

      # Start a Slack workflow using a webhook trigger
      # https://github.com/slackapi/slack-github-action
      - name: Send GitHub Action trigger data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.16.0
        with:
          payload: |
            {
              "text": ":github: ${{ github.event_name }}@${{ github.event.pull_request.html_url || github.event.head_commit.url }}\n${{ steps.check.outputs.comment_body }}\nby ${{ github.event.sender.login }}"
            }
        env:
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_INCOMING_WEBHOOK_URL }}
